### ISSUE TITLE
Add transparency slider

### ISSUE THREAD

**Issue by Ainali** [Abbe98/commons-warper-viewer.js#1]
This user script would be greatly enhanced if there was a slider for the transparency. The one used in the wikimaps warper is perfectly fine, all you need really is a way to easy see how the overlayed map matches the underlying (modern) features.

**Comment by Abbe98** [comment]
Note to self:
- do this in wikimaps-dev/warped-to-iframe
- add a parameter for Wikimedia Maps layer **DONE**
- update to Leaflet 1.0 **BLOCKED** as discussed on #wikimedia-labs IRC
- write a slider from scratch (`L.Control.extend`) **DONE**
- if turns out to be a relay nice slider it should be a plugin. 
- make the slider optional by adding another parameter **DONE**
- update the docs
- actually update the request URL in this repo **DONE**
